### PR TITLE
I accidentally forked this project. Soucery AI refactored it

### PR DESCRIPTION
**Pull request by Advik-B**
This is a VERY COOL project

### CODE REVIEW

**Comment by Advik-B** [comment]
apparently my pull makes it faster

**Comment by Advik-B** [comment]
@pokepetter ? hello?

**Comment by pokepetter** [comment]
Oh, it was an accident? Just close it then.

**Comment by Advik-B** [comment]
@pokepetter the thing is... i have an app called [sourcery AI](https://sourcery.ai/) and it refactored it
soooo... I am guessing that it is a performance upgrade

**Pull request closed without merging**
