### PR TITLE
fixed index out of range bug

### PR DESCRIPTION
**Pull request by y2bad**
fixed index error when clicking at the very lower edge of the button list

### CODE REVIEW

**Comment by pokepetter** [comment]
How did you get index out of range in the first place?

**Comment by y2bad** [comment]
I just ran the example code and when i hover over the bottom edge the selector goes outside of the list. I can send you a video on discord if you want.

**Comment by y2bad** [comment]
just found out you can post videos on here too

https://github.com/pokepetter/ursina/assets/75477334/5449ea80-24bb-48e8-9023-b25f69d3fe13

**Comment by pokepetter** [comment]
Wasn't able to reproduce it, but it it fixes it I'll merge it it ^^

**Pull request merged**
