### PR TITLE
Add a NineSlice from Mesh class, to create scalable textures

### PR DESCRIPTION
**Pull request by PaologGithub**
A NineSlice texture is to cut the texture in nine, like this:
4 Corners
4 Borders
1 Middle

With this, you can use one 32x32 texture, to make buttons that have the same texture, but not streched or squeeshed.

This pull request add a new NineSlice class, that is based from the Mesh class.
It adds too a nine_sliced texture, so we can see the nine cuts.

### CODE REVIEW

**Comment by pokepetter** [comment]
I already have a work in progress for nine-slice, that also supports 3D. I guess you could call it 27-slice. However, this could be nice to have right now. Needs some small change though. The script should be in ursina/models/procedural/ alongside the other procedural models.

**Comment by PaologGithub** [comment]
Did it

**Comment by PaologGithub** [comment]
Thanks :,)

**Comment by pokepetter** [comment]
@PaologGithub The corners and edges doesn't seem to have a consistent size, even though both entities have the same scale.
The entity to the left has smaller corners, even though the point of a nine slice is to keep this consistent.
image

**Comment by PaologGithub** [comment]
> @PaologGithub The corners and edges doesn't seem to have a consistent size, even though both entities have the same scale. The entity to the left has smaller corners, even though the point of a nine slice is to keep this consistent. image

Yeah, that's not the best option. I don't know how can I change that, because I change the model

**Pull request merged**
