### PR TITLE
Reupdated sqrt

### PR DESCRIPTION
**Pull request by Tech-Helper503**

### CODE REVIEW

**Comment by pokepetter** [comment]
Seems to give a completely wrong result:
```
e1 = Entity(position = (0,0,0))
e2 = Entity(position = (0,10,10))
print(distance(e1, e2))
print(distance_xz(e1, e2.position))
```
Before:
```
14.142135623730951
10.0
```
After:
```
200.0
0.1
```

**Comment by Tech-Helper503** [comment]
Thanks for the info... I have reupdated it.

**Comment by pokepetter** [comment]
I still don't get it. You added a function that's not used anywhere and duplicated a line?

**Comment by Tech-Helper503** [comment]
Well, I've added the function as a feature update

**Pull request closed without merging**
