### PR TITLE
added missing docs

### PR DESCRIPTION
**Pull request by ValleyDragon888**
added descriptions of some Entity paramerters

### CODE REVIEW

**Comment by ValleyDragon888** [comment]
Hi!
I have had lot of fun using ursina, so I thought I should help with the documentation.
Could someone explain the difference between `.parameter` and `.world_parameter` (e.g. world_scale and scale) so that I can add it in?

**Comment by pokepetter** [comment]
This will get reverted once the documentation gets regenerated.

**Comment by ValleyDragon888** [comment]
Yeah I have just realised that. Fixing!

**Comment by pokepetter** [comment]
The issue is not with missing docs. Often the setters have comments while the getter does not. Having duplicated docs is not good either. The solution is to fix the documentation generator, which I'm working on. Also, some of your descriptions are wrong/inaccurate.

**Pull request closed without merging**
